# Generated by Django 4.2.4 on 2023-08-25 05:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Title', models.CharField(max_length=200)),
                ('Material_Summary', models.TextField()),
                ('Material_Last_Updated_Date', models.DateTimeField(auto_now=True)),
                ('Materail_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Material_Published_Status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Unpublished', max_length=20)),
                ('Material_Slug', models.SlugField(blank=True, max_length=10, null=True)),
                ('Material_Document_File', models.FileField(blank=True, null=True, upload_to='FileApp/Document', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'csv', 'xls', 'ppt', 'html'])])),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaterialCategory_Name', models.CharField(max_length=500)),
                ('DocumentCategory_Status', models.BooleanField(default=False)),
                ('MaterialCategory_CreationDate', models.DateField(auto_now_add=True)),
                ('MaterialCategory_LastUpdatedDate', models.DateField(auto_now=True)),
                ('MaterialCategory_PublishedStatus', models.CharField(choices=[('Published', 'PUBLISHED'), ('Unpublished', 'UNPUBLISHED')], default='Unpublished', max_length=20)),
                ('MaterialCategory_Author', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'MaterialCategories',
                'ordering': ['MaterialCategory_Name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approval_Status', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('---', '---')], default='---', max_length=20)),
                ('Material_Approval_Request_Date', models.DateTimeField(auto_now_add=True)),
                ('Material_Approval_Date', models.DateTimeField(blank=True, null=True)),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileApp.material', verbose_name='Material')),
                ('Requested_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requested User')),
            ],
            options={
                'verbose_name_plural': 'Material Approval',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='Material_CategoryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileApp.materialcategory'),
        ),
        migrations.AddField(
            model_name='material',
            name='Material_Contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Material Contributor'),
        ),
    ]
