# Generated by Django 4.2.4 on 2023-08-23 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Title', models.CharField(max_length=200)),
                ('Material_Contributor', models.CharField(max_length=200)),
                ('Material_Summary', models.TextField()),
                ('Material_Last_Updated_Date', models.DateTimeField(auto_now=True)),
                ('Materail_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Material_Published_Status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Unpublished', max_length=20)),
                ('Material_Slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('Material_Document_File', models.FileField(blank=True, null=True, upload_to='FileApp/Document', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'csv', 'xls', 'ppt', 'html'])])),
            ],
            options={
                'verbose_name_plural': 'Material',
            },
        ),
    ]
