# Generated by Django 4.2.4 on 2023-08-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcategory',
            old_name='DocumentCategory_Status',
            new_name='MaterialCategory_Status',
        ),
    ]
