# Generated by Django 4.2.4 on 2023-08-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Material_Slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
