# Generated by Django 4.2.4 on 2023-08-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileApp', '0003_alter_material_material_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='Material_Slug',
        ),
    ]
