# Generated by Django 4.2.4 on 2023-08-24 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FileApp', '0005_material_material_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Material_Contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Material Contributor'),
        ),
    ]
